stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cp .env.sample .env
    - docker compose build

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
  script:
    - cp .env.sample .env
    - echo "TEST=1" >> .env
    - docker compose up -d
    - sleep 30
    - docker logs flicker-app 2> flicker-app.log
    - docker compose down
    - (! grep "FAIL" clifker-app.log)
  artifacts:
    paths:
      - app.log
    when: always

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
