stages:
  - build
  - test

build:
  stage: build
  only:
    - main
  image: docker:latest
  services:
    - docker:dind
  script:
    - cp .env.sample .env
    - docker compose build

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
  script:
    - cp .env.sample .env
    - echo -e "\nTEST_FLAG=true" >> .env
    - cat .env
    - docker compose up -d
    - sleep 20
    - docker logs flicker-app 1> flicker-app.log
    - echo -e "\n\n\n^^^  STDOUT  ^^^\n========================\nvvv  STDERR  vvv\n\n\n" >> flicker-app.log
    - docker logs flicker-app 2>> flicker-app.log
    - docker compose down
    - (! grep "FAIL" flicker-app.log)
  artifacts:
    paths:
      - flicker-app.log
    when: always

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
