stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  script:
    - cp .env.sample .env
    - docker info
    - docker compose build

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  script:
    - cp .env.sample .env
    - echo "TEST=1" >> .env
    - docker compose up -d
    - sleep 30
    - docker logs app 2> app.log
    - docker compose down
    - (! grep "FAIL" app.log)
  artifacts:
    paths:
      - app.log
    when: always

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
