services:
  app:
    build:
      context: .
    restart: no
    container_name: flicker-app
    ports:
      - 8000:8000
    volumes:
      - static-data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY:-devsecretkey}
      - DEBUG=${DEBUG:-false}
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-devdb}
      - DB_USER=${DB_USER:-devuser}
      - DB_PASS=${DB_PASS:-changeme}
      - TEST_FLAG=${TEST_FLAG:-false}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    container_name: flicker-db
    environment:
      - POSTGRES_DB=${DB_NAME:-devdb}
      - POSTGRES_USER=${DB_USER:-devuser}
      - POSTGRES_PASSWORD=${DB_PASS:-changeme}

  proxy:
    build:
      context: ./proxy
    restart: always
    container_name: flicker-proxy
    depends_on:
      - app
    ports:
      - "80:8000"
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data:
