# Generated by Django 5.0.7 on 2024-08-01 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flicker_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastCrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField()),
                ('content_url', models.URLField()),
                ('release_year', models.IntegerField()),
                ('runtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GenreMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flicker_core.genre')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flicker_core.mediaobject')),
            ],
        ),
        migrations.CreateModel(
            name='Credited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credited_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flicker_core.castcrewmember')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flicker_core.mediaobject')),
            ],
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flicker_core.mediarating'),
        ),
        migrations.AddField(
            model_name='mediaobject',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flicker_core.season'),
        ),
        migrations.AddField(
            model_name='season',
            name='parent_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flicker_core.show'),
        ),
    ]
