# Generated by Django 5.1 on 2024-08-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flicker_core', '0004_flickeruser_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickeruser',
            name='subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
